-- Create SonarQube configuration table
CREATE TABLE IF NOT EXISTS sonarqube_config (
  id BIGINT PRIMARY KEY AUTO_INCREMENT,
  base_url VARCHAR(1024) NOT NULL,
  api_token VARCHAR(512),
  created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
);

